#!/bin/bash

currentBranch=$(git rev-parse --abbrev-ref HEAD)
scope=$currentBranch

isSpecialBranchTest=$(echo "$currentBranch" | grep -c -E "main|master|develop|forno")
zero=0
if [ $isSpecialBranchTest -eq $zero ]; then
        scope=$(echo "$currentBranch" | cut -d'/' -f 2)
fi

type=$1

shift 1

subject=$*

git commit -m "$type($scope): $subject"
