#!/bin/bash

currentBranch=$(git rev-parse --abbrev-ref HEAD);
scope=$currentBranch;

if [ "$currentBranch" != "develop" ] && [ "$currentBranch" != "master" ] && [ "$currentBranch" != "main" ] && [ "$currentBranch" != "forno" ]; then
        scope=$(echo $currentBranch | cut -d'/' -f 2)
fi

type=$1;

shift 1;

subject=$*;

git commit -m "$type ($scope): $subject";
